server:
  port: 8080
  servlet:
    session:
      timeout: 10800s
    multipart:
      max-file-size: 102400Mb
      max-request-size: 102400Mb
spring:
  application:
    name: securityDemo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sbs-demo?userUnicode=true&characterEncoding=UTF8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  #    schema: classpath:sbs-demo.sql
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jin.demo.entity


logging:
  config: classpath:logback-spring.xml
